// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe7KUuEpPwvN1KALc40aEu_Wdb4Yx7Ehc',
    appId: '1:1078259449443:web:136400450343d015fe4256',
    messagingSenderId: '1078259449443',
    projectId: 'local-plant-identification',
    authDomain: 'local-plant-identification.firebaseapp.com',
    storageBucket: 'local-plant-identification.firebasestorage.app',
    measurementId: 'G-HSVE027QK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6zHZ2Zk8XYhQ3k3Ntx49NkwsXjmCN7xY',
    appId: '1:1078259449443:android:8caad42172f14bb6fe4256',
    messagingSenderId: '1078259449443',
    projectId: 'local-plant-identification',
    storageBucket: 'local-plant-identification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFGE0BbyvO0uTXvGCf9dAg7N_rOlCiTcc',
    appId: '1:1078259449443:ios:f5c61e437280cdcbfe4256',
    messagingSenderId: '1078259449443',
    projectId: 'local-plant-identification',
    storageBucket: 'local-plant-identification.firebasestorage.app',
    iosBundleId: 'com.example.localPlantIdentification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFGE0BbyvO0uTXvGCf9dAg7N_rOlCiTcc',
    appId: '1:1078259449443:ios:f5c61e437280cdcbfe4256',
    messagingSenderId: '1078259449443',
    projectId: 'local-plant-identification',
    storageBucket: 'local-plant-identification.firebasestorage.app',
    iosBundleId: 'com.example.localPlantIdentification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe7KUuEpPwvN1KALc40aEu_Wdb4Yx7Ehc',
    appId: '1:1078259449443:web:b7619c154b28553afe4256',
    messagingSenderId: '1078259449443',
    projectId: 'local-plant-identification',
    authDomain: 'local-plant-identification.firebaseapp.com',
    storageBucket: 'local-plant-identification.firebasestorage.app',
    measurementId: 'G-7G3327LGTQ',
  );
}
